server.port=8081

spring.application.name=user-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=kartik
spring.datasource.password=olokar
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

management.endpoints.web.exposure.include=*
